spring.datasource.url=jdbc:h2:mem:helpdesk_center;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

watson.nlu.api-key=${WATSON_API_KEY:}
watson.nlu.url=${WATSON_URL:}

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=warn
logging.level.org.hibernate.orm.jdbc.bind=warn
logging.level.org.springframework.mail=warn
